name: megin auto satege to main

on:
  pull_request:
    branches:
      - stage
    types:
      - synchronize

jobs:
  merge-to-main:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Checkout stage branch
        run: git checkout stage

      - name: Merge stage into main
        run: |
          git checkout main
          git merge stage

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: git push origin main

      - name: validate process completed
        run: echo "Process completed successfully"
